spring:
  security:
    oauth2:
      client:
        post-logout:
          registration:
            helseid:
              redirect-uri: http://localhost:3000
        jwt:
          registration:
            helseid:
              private-key: private-key.pem
            helseid-machine:
              private-key: private-key.pem
        registration:
          helseid:
            client-authentication-method: private_key_jwt
          helseid-machine:
            client-authentication-method: private_key_jwt