spring:
  security:
    oauth2:
      client:
        post-logout:
          registration:
            helseid:
              redirect-uri: http://localhost:3000
        jwt:
          registration:
            helseid:
              private-key: private-key.pem
              public-key: public-key.pem
            helseid-machine:
              private-key: ${spring.security.oauth2.client.jwt.registration.helseid.private-key}
              public-key: ${spring.security.oauth2.client.jwt.registration.helseid.public-key}
        registration:
          helseid:
            client-authentication-method: private_key_jwt
          helseid-machine:
            client-authentication-method: private_key_jwt

