spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${helseid.sts.uri}/.well-known/openid-configuration/jwks
          issuer-uri: ${helseid.sts.uri}
      client:
        detail:
          registration:
            helseid-credentials:
              private-key: private-key-credentials.json
              #org-number: "999977775"
        registration:
          helseid-credentials:
            client-authentication-method: private_key_jwt
            authorization-grant-type: client_credentials
            scope: [ 'nhn:helseid-public-samplecode/client-credentials' ]
            client-id: helseid-sample-client-credentials
            client-name: ${helseid.registration-name.machine}
        provider:
          helseid-credentials:
            token-uri: ${helseid.sts.uri}/connect/token
helseid:
  registration-name:
    machine: helseid-credentials
  sts:
    uri: https://helseid-sts.test.nhn.no
